# Generated by Django 4.2 on 2023-04-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_cart_product_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Published',
        ),
    ]
