# Generated by Django 4.2 on 2023-04-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_remove_product_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ProductBrand',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='ProductName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='ProductSpecs',
            new_name='Specs',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductBrand',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductSpecs',
            new_name='Specs',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Published',
        ),
    ]
